# Generated by Django 3.1 on 2020-08-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('domain', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='homeblog')),
                ('offer_tag', models.CharField(blank=True, max_length=50)),
                ('item_domain', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.company')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'Contents',
            },
        ),
    ]
