# Generated by Django 3.1 on 2020-08-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_auto_20200821_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.category'),
        ),
    ]
