# Generated by Django 3.1 on 2020-08-25 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0004_auto_20200821_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'Companies'},
        ),
    ]
