# Generated by Django 3.1 on 2020-08-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeblog', '0003_auto_20200825_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
